apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: selenium-queue-exporter
  namespace: selenium
spec:
  selector:
    matchLabels:
      app: selenium-queue-exporter
  endpoints:
  - port: web
    interval: 10s