apiVersion: apps/v1
kind: Deployment
metadata:
  name: scalable-web-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scalable-web-server
  template:
    metadata:
      labels:
        app: scalable-web-server
    spec:
      containers:
      - name: webserver
        image: andreathesis/scalable-web-server
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: 10m
          limits:
            cpu: 20m

---

apiVersion: v1
kind: Service
metadata:
  name: scalable-web-server-svc
spec:
  selector:
    app: scalable-web-server
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: scalable-web-server-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: scalable-web-server
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20