apiVersion: apps/v1
kind: Deployment
metadata:
  name: sws
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sws
  template:
    metadata:
      labels:
        app: sws
    spec:
      containers:
      - name: webserver
        image: andreathesis/sws
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 200m

---

apiVersion: v1
kind: Service
metadata:
  name: sws-svc
spec:
  selector:
    app: sws
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer

---

apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: sws-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sws
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 20