apiVersion: apps/v1
kind: Deployment
metadata:
  name: scraper
  namespace: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scraper
  template:
    metadata:
      labels:
        app: scraper
    spec:
      containers:
      - name: scraper
        image: andreathesis/scraper
        