apiVersion: apps/v1
kind: Deployment
metadata:
  name: selenium-hub
  namespace: selenium
spec:
  replicas: 1
  selector:
    matchLabels:
      app: selenium-hub
  template:
    metadata:
      labels:
        app: selenium-hub
    spec:
      containers:
      - name: selenium-hub
        image: selenium/hub:4.1.0
        ports:
        - containerPort: 4444
          protocol: TCP
        - containerPort: 4443
          protocol: TCP
        - containerPort: 4442
          protocol: TCP
        resources:
          requests:
            memory: "512Mi"
            cpu: "512m"
          limits:
            memory: "1Gi"
            cpu: "1"

---

apiVersion: v1
kind: Service
metadata:
  name: selenium-hub
  namespace: selenium
  labels:
    app: selenium-hub
spec:
  ports:
  - port: 4443
    targetPort: 4443
    name: port1
  - port: 4442
    targetPort: 4442
    name: port2
  - port: 4444
    targetPort: 4444
    name: port3
  selector:
    app: selenium-hub
  type: LoadBalancer

